import type { Metadata } from "next";
import { Inter, Roboto, Open_Sans, Lato, Outfit } from "next/font/google";
import "./globals.css";
import "../lib/fontawesome";

const outfit = Outfit({
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pasar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} size-full`}>
        <div className="max-w-md mx-auto h-screen">{children}</div>
      </body>
    </html>
  );
}
